name: Deploiement site statique

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout du code
              uses: actions/checkout@v3

            - name: Installation de Node.js
              uses: actions/setup-node@v3

            - name: Installation des dépendances
              run: npm install

            - name: Exécution des tests
              run: npm test

    deploy:
        needs: test
        runs-on: ubuntu-latest
        steps:
            - name: Checking repository
              uses: actions/checkout@v3

            - name: Deploy to VPS
              uses: appleboy/scp-action@master
              with:
                  host: ${{ secrets.VPS_HOST }}
                  username: ${{ secrets.HOST_USER }}
                  key: ${{ secrets.VPS_SSH_KEY }}
                  port: ${{ secrets.VPS_PORT }}
                  source: "."
                  target: "/home/nolann/test_gta"
